<?php
return [
    'app' => [
        'name' => 'SignalOps Status',
        'subtitle' => 'PHP Based status dashboard for Discord bots, trading services, and private server fleets.',
        'timezone' => 'America/Toronto',
        'demo' => false,
        'theme' => [
            'accent' => '#20b981',
            'repository_url' => 'https://github.com/tuolaji996/SignalOps-Status',
            'owner_name' => 'Your Team',
            'owner_url' => 'https://example.com',
        ],
    ],
    'cache' => [
        'enabled' => true,
        'seconds' => 15,
        'stale_seconds' => 300,
        'refresh_lock_seconds' => 20,
        'browser_max_age' => 5,
        'stale_while_revalidate' => 60,
        'cdn' => [
            'enabled' => false,
            'edge_max_age' => 60,
            'stale_while_revalidate' => 300,
            'stale_if_error' => 604800,
        ],
        'path' => '/var/lib/signalops-status/status-cache.json',
    ],
    'sla' => [
        'enabled' => true,
        'path' => '/var/lib/signalops-status/ping-sla.json',
        'ping_timeout_seconds' => 1,
    ],
    'traffic' => [
        'enabled' => true,
        'path' => '/var/lib/signalops-status/network-usage.json',
    ],
    'database' => [
        'enabled' => true,
        'label' => 'Database Server',
        'dsn' => 'mysql:host=DATABASE_PRIVATE_HOST;port=3306;dbname=signals;charset=utf8mb4',
        'user' => 'status_readonly',
        'password' => 'put-readonly-password-here',
        'summary_sql' => "SELECT COUNT(*) AS event_count, MAX(seen_at) AS latest_event_at FROM signal_events",
        'recent_sql' => "SELECT seen_at, kind, symbol, text FROM signal_events ORDER BY seen_at DESC LIMIT 8",
    ],
    'endpoints' => [
        'discord' => [
            'label' => 'Discord Bot',
            'url' => 'http://DISCORD_BOT_PRIVATE_HOST:8790/health.json',
            'kind' => 'discord',
        ],
        'api' => [
            'label' => 'Trading API',
            'url' => 'http://TRADING_API_PRIVATE_HOST:8787/health.json',
            'kind' => 'api',
        ],
    ],
    'machines' => [
        [
            'key' => 'web',
            'label' => 'Web Server',
            'role' => 'Status frontend',
            'location' => 'Los Angeles, CA',
            'kind' => 'local',
            'network_iface' => 'tailscale0',
            'sla_host' => '127.0.0.1',
            'latency_targets' => [
                'db' => 'DATABASE_PRIVATE_HOST',
                'discord' => 'DISCORD_BOT_PRIVATE_HOST',
                'api' => 'TRADING_API_PRIVATE_HOST',
            ],
            'disks' => ['/'],
            'services' => ['nginx'],
        ],
        [
            'key' => 'db',
            'label' => 'Database Server',
            'role' => 'Long-term archive',
            'location' => 'Chicago, IL',
            'kind' => 'ssh',
            'host' => 'DATABASE_PRIVATE_HOST',
            'sla_host' => 'DATABASE_PRIVATE_HOST',
            'user' => 'root',
            'key_file' => '/etc/signalops-status/status_probe_ed25519',
            'latency_targets' => [
                'web' => 'WEB_PRIVATE_HOST',
                'discord' => 'DISCORD_BOT_PRIVATE_HOST',
                'api' => 'TRADING_API_PRIVATE_HOST',
            ],
            'disks' => ['/', '/var/lib/mysql'],
            'services' => ['mysql'],
        ],
        [
            'key' => 'discord',
            'label' => 'Discord Bot Server',
            'role' => 'Bot runtime',
            'location' => 'Toronto, ON',
            'kind' => 'ssh',
            'host' => 'DISCORD_BOT_PRIVATE_HOST',
            'sla_host' => 'DISCORD_BOT_PRIVATE_HOST',
            'user' => 'root',
            'key_file' => '/etc/signalops-status/status_probe_ed25519',
            'latency_targets' => [
                'web' => 'WEB_PRIVATE_HOST',
                'db' => 'DATABASE_PRIVATE_HOST',
                'api' => 'TRADING_API_PRIVATE_HOST',
            ],
            'disks' => ['/opt/discord-bot', '/'],
            'services' => ['discord-bot.service'],
            'journal_units' => ['discord-bot.service'],
        ],
        [
            'key' => 'api',
            'label' => 'Trading API Server',
            'role' => 'Market data capture',
            'location' => 'Toronto, ON',
            'kind' => 'ssh',
            'host' => 'TRADING_API_PRIVATE_HOST',
            'sla_host' => 'TRADING_API_PRIVATE_HOST',
            'user' => 'root',
            'key_file' => '/etc/signalops-status/status_probe_ed25519',
            'latency_targets' => [
                'web' => 'WEB_PRIVATE_HOST',
                'db' => 'DATABASE_PRIVATE_HOST',
                'discord' => 'DISCORD_BOT_PRIVATE_HOST',
            ],
            'disks' => ['/'],
            'services' => ['trading-api.service'],
            'journal_units' => ['trading-api.service'],
        ],
    ],
    'latency_map' => [
        'enabled' => true,
        'nodes' => [
            'web' => ['label' => 'Web Server', 'location' => 'Los Angeles, CA', 'x' => 15, 'y' => 65],
            'db' => ['label' => 'Database Server', 'location' => 'Chicago, IL', 'x' => 58, 'y' => 45],
            'discord' => ['label' => 'Discord Bot Server', 'location' => 'Toronto, ON', 'x' => 80, 'y' => 47],
            'api' => ['label' => 'Trading API Server', 'location' => 'Toronto, ON', 'x' => 75, 'y' => 27],
        ],
        'links' => [
            ['from' => 'web', 'to' => 'db', 'source' => 'web', 'target' => 'db', 'label' => 'Web to Database'],
            ['from' => 'web', 'to' => 'discord', 'source' => 'web', 'target' => 'discord', 'label' => 'Web to Discord'],
            ['from' => 'web', 'to' => 'api', 'source' => 'web', 'target' => 'api', 'label' => 'Web to Trading API'],
            ['from' => 'db', 'to' => 'discord', 'source' => 'db', 'target' => 'discord', 'label' => 'Database to Discord'],
            ['from' => 'discord', 'to' => 'api', 'source' => 'discord', 'target' => 'api', 'label' => 'Discord to Trading API'],
        ],
    ],
];
